#!/usr/bin/env bash

# bump the version
cd projects/ngx-message
VERSION="$(npm version patch)"
cd ../..

# build the lib
ng build ngx-message
cp README.md LICENSE dist/ngx-message/

# build the demo
ng build ngx-message-demo  --prod --aot --baseHref /ngx-message/

# build the docs
compodoc  -p projects/ngx-message/tsconfig.lib.json  --disableCoverage --output docs/docs 


# publish to NPM
cd dist/ngx-message
npm publish --access public
cd ../..


# commit with tag
git add -A
git commit -m "published version ${VERSION} to npm"
git tag  $VERSION
git push
git push --tags
